/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Admin
 */
public class FlightInfomation extends javax.swing.JFrame {
	 // Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel LABEL_1;
    private javax.swing.JLabel LABEL_2;
    private javax.swing.JLabel LABEL_3;
    private javax.swing.JLabel LABEL_4;
    private javax.swing.JLabel LABEL_5;
    private javax.swing.JLabel LABEL_6;
    private javax.swing.JLabel LABEL_7;
    private javax.swing.JLabel LABEL_8;
    private javax.swing.JLabel LABEL_9;
    private javax.swing.JLabel LABEL_10;
    public javax.swing.JLabel AIRLINE;
    public javax.swing.JLabel AIRLINE_CODE;
    public javax.swing.JLabel ARRIVE_TIME;
    public javax.swing.JButton BACK;
    public javax.swing.JButton BOOK_TICKET;
    public javax.swing.JLabel END_CITY;
    public javax.swing.JLabel FLIGHTDAY;
    public javax.swing.JLabel HEADER;
    public javax.swing.JLabel ORIGINAL_PRICE;
    public javax.swing.JLabel PLANE;
    public javax.swing.JLabel PRICE_AFTER_TAX;
    public javax.swing.JLabel START_CITY;
    public javax.swing.JLabel START_TIME;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form FlightInfomation
     */
    public FlightInfomation() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        HEADER = new javax.swing.JLabel();
        LABEL_6 = new javax.swing.JLabel();
        LABEL_7 = new javax.swing.JLabel();
        LABEL_5 = new javax.swing.JLabel();
        LABEL_1 = new javax.swing.JLabel();
        LABEL_3 = new javax.swing.JLabel();
        LABEL_4 = new javax.swing.JLabel();
        LABEL_2 = new javax.swing.JLabel();
        LABEL_8 = new javax.swing.JLabel();
        LABEL_10 = new javax.swing.JLabel();
        LABEL_9 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        BOOK_TICKET = new javax.swing.JButton();
        END_CITY = new javax.swing.JLabel();
        AIRLINE = new javax.swing.JLabel();
        START_CITY = new javax.swing.JLabel();
        AIRLINE_CODE = new javax.swing.JLabel();
        FLIGHTDAY = new javax.swing.JLabel();
        ARRIVE_TIME = new javax.swing.JLabel();
        ORIGINAL_PRICE = new javax.swing.JLabel();
        START_TIME = new javax.swing.JLabel();
        PRICE_AFTER_TAX = new javax.swing.JLabel();
        PLANE = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1000, 600));
        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(500, 200);

        HEADER.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        HEADER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADER.setText("THONG TIN CHUYEN BAY");

        LABEL_6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_6.setText("GIO BAY:");

        LABEL_7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_7.setText("GIO DEN:");

        LABEL_5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_5.setText("NGAY BAY : ");

        LABEL_1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LABEL_1.setText("HANG: ");

        LABEL_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LABEL_3.setText("TU: ");

        LABEL_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LABEL_4.setText("DEN: ");

        LABEL_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LABEL_2.setText("MA CHUYEN BAY: ");

        LABEL_8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_8.setText("MAY BAY: ");

        LABEL_10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_10.setText("GIA + THUE :");

        LABEL_9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LABEL_9.setText("GIA:");

        BACK.setText("TRO LAI");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        BOOK_TICKET.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        BOOK_TICKET.setText("DAT VE");

        END_CITY.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        

        AIRLINE.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
   

        START_CITY.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
 

        AIRLINE_CODE.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
  

        FLIGHTDAY.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
       

        ARRIVE_TIME.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N


        ORIGINAL_PRICE.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N


        START_TIME.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
   

        PRICE_AFTER_TAX.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
     

        PLANE.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
      

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOOK_TICKET, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 439, 439))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABEL_3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(END_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AIRLINE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(START_CITY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(AIRLINE_CODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LABEL_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LABEL_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LABEL_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FLIGHTDAY, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ARRIVE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(START_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LABEL_10, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(LABEL_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LABEL_8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ORIGINAL_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PRICE_AFTER_TAX, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PLANE, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AIRLINE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FLIGHTDAY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PLANE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AIRLINE_CODE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(START_TIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ORIGINAL_PRICE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ARRIVE_TIME, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(PRICE_AFTER_TAX, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(START_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LABEL_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(END_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(BOOK_TICKET, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    public static void main(String[] args) {
		new FlightInfomation();
	}
   
}
